services:
  gluetun-qbittorrent:
    image: qmcgaw/gluetun:v3.40
    container_name: gluetun-qbittorrent
    hostname: qbittorrent
    cap_add:
      - NET_ADMIN
    ports:
      - "8080:8080"
    volumes:
      - gluetun:/gluetun
    networks:
      - jellyfin
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      VPN_SERVICE_PROVIDER: protonvpn
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY}
      VPN_PORT_FORWARDING: true
      VPN_PORT_FORWARDING_UP_COMMAND: /bin/sh -c 'wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{PORTS}}}" http://127.0.0.1:8080/api/v2/app/setPreferences 2>&1'
    restart: unless-stopped
    labels:
      glance.parent: qbittorrent
      glance.name: ProtonVPN (Gluetun)

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:5.0.4
    container_name: qbittorrent
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      WEBUI_PORT: 8080
      TORRENTING_PORT: 6881
    volumes:
      - ${VOLUMES_DIR}/qbittorrent/config:/config
      - /mnt/hdd1/downloads:/downloads
    depends_on:
      - gluetun-qbittorrent
    network_mode: service:gluetun-qbittorrent
    restart: unless-stopped
    labels:
      glance.id: qbittorrent
      glance.name: qBittorrent
      glance.icon: sh:qbittorrent

volumes:
  gluetun:

networks:
  jellyfin:
    external: true
