services:
  tailscale-gluetun-qbittorrent:
    image: tailscale/tailscale:v1.80
    container_name: tailscale-gluetun-qbittorrent
    hostname: qbittorrent
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY}?ephemeral=false
      TS_EXTRA_ARGS: --advertise-tags=tag:container
      TS_STATE_DIR: /var/lib/tailscale
      TS_SERVE_CONFIG: /config/qbittorrent.json
    volumes:
      - ${VOLUMES_DIR}/qbittorrent/tailscale:/config
      - tailscale:/var/lib/tailscale
    networks:
      - jellyfin
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
    labels:
      glance.parent: qbittorrent
      glance.name: Tailscale

  gluetun-qbittorrent:
    image: qmcgaw/gluetun:v3.40
    container_name: gluetun-qbittorrent
    cap_add:
      - NET_ADMIN
    volumes:
      - gluetun:/gluetun
    network_mode: service:tailscale-gluetun-qbittorrent
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      VPN_SERVICE_PROVIDER: protonvpn
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY}
      VPN_PORT_FORWARDING: true
      VPN_PORT_FORWARDING_UP_COMMAND: /bin/sh -c 'wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{PORTS}}}" http://127.0.0.1:8080/api/v2/app/setPreferences 2>&1'
    restart: unless-stopped
    labels:
      glance.parent: qbittorrent
      glance.name: ProtonVPN (Gluetun)

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:5.0.4
    container_name: qbittorrent
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      WEBUI_PORT: 8080
      TORRENTING_PORT: 6881
    volumes:
      - ${VOLUMES_DIR}/qbittorrent/config:/config
      - /mnt/hdd1/downloads:/downloads
    depends_on:
      - gluetun-qbittorrent
    network_mode: service:gluetun-qbittorrent
    restart: unless-stopped
    labels:
      glance.id: qbittorrent
      glance.name: qBittorrent
      glance.icon: sh:qbittorrent
      glance.url: https://qbittorrent.owl-augmented.ts.net/

volumes:
  gluetun:
  tailscale:

networks:
  jellyfin:
    external: true
