services:
  tailscale-prowlarr:
    image: tailscale/tailscale
    container_name: tailscale-prowlarr
    hostname: prowlarr
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY}?ephemeral=false
      TS_EXTRA_ARGS: --advertise-tags=tag:container
      TS_STATE_DIR: /var/lib/tailscale
      TS_SERVE_CONFIG: /config/prowlarr.json
    volumes:
      - ${VOLUMES_DIR}/prowlarr/tailscale:/config
      - tailscale:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    networks:
      - jellyfin
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${VOLUMES_DIR}/prowlarr/config:/config
    depends_on:
      - tailscale-prowlarr
    network_mode: service:tailscale-prowlarr
    restart: unless-stopped

volumes:
  tailscale:

networks:
  jellyfin:
    external: true
