services:
  corentinth:
    image: 'ghcr.io/corentinth/it-tools:latest'
    container_name: it-tools
    networks:
      - proxy
    restart: unless-stopped
    labels:
      # traefik
      traefik.enable: true
      traefik.http.routers.it-tools.rule: Host(`it.ryanmalonzo.com`)
      traefik.http.routers.it-tools.entrypoints: websecure
      traefik.http.routers.it-tools.tls.certresolver: cloudflare
      traefik.http.services.it-tools.loadbalancer.server.port: 80
      # glance
      glance.name: IT Tools
      glance.icon: sh:it-tools
      glance.url: https://it.ryanmalonzo.com/

networks:
  proxy:
    external: true
