services:
  ocis:
    image: owncloud/ocis:7.0.1
    volumes:
      - ${VOLUMES_DIR}/owncloud/ocis.yaml:/etc/ocis/ocis.yaml
      - ${VOLUMES_DIR}/owncloud/ocis:/var/lib/ocis
    environment:
      OCIS_INSECURE: true
      OCIS_URL: https://owncloud.ryanmalonzo.com
      OCIS_LOG_LEVEL: info
      PROXY_HTTP_ADDR: 0.0.0.0:9200
    networks:
      - proxy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.owncloud.rule=Host(`owncloud.ryanmalonzo.com`)"
      - "traefik.http.routers.owncloud.entrypoints=websecure"
      - "traefik.http.routers.owncloud.tls.certresolver=cloudflare"
      - "traefik.http.services.owncloud.loadbalancer.server.port=9200"

networks:
  proxy:
    external: true
