services:
  ocis:
    image: owncloud/ocis:7.0.1
    container_name: owncloud
    volumes:
      - ${VOLUMES_DIR}/owncloud:/etc/ocis
      - ocis:/var/lib/ocis
    environment:
      # proxy
      OCIS_INSECURE: true
      OCIS_URL: https://owncloud.ryanmalonzo.com
      OCIS_LOG_LEVEL: info
      PROXY_HTTP_ADDR: 0.0.0.0:9200
      PROXY_TLS: false
      # oidc
      OCIS_OIDC_ISSUER: https://id.ryanmalonzo.com
      OCIS_OIDC_CLIENT_ID: 309184241151836163
      PROXY_OIDC_REWRITE_WELLKNOWN: true
      PROXY_OIDC_ACCESS_TOKEN_VERIFY_METHOD: none
      PROXY_ROLE_ASSIGNMENT_OIDC_CLAIM: custom:roles
      PROXY_USER_OIDC_CLAIM: preferred_username
      PROXY_AUTOPROVISION_ACCOUNTS: true
      PROXY_ROLE_ASSIGNMENT_DRIVER: oidc
      # config
      PROXY_CSP_CONFIG_FILE_LOCATION: /etc/ocis/csp.yaml
      OCIS_SHARING_PUBLIC_SHARE_MUST_HAVE_PASSWORD: false
    networks:
      - proxy
    restart: unless-stopped
    labels:
      # traefik
      traefik.enable: true
      traefik.http.routers.owncloud.rule: Host(`owncloud.ryanmalonzo.com`)
      traefik.http.routers.owncloud.entrypoints: websecure
      traefik.http.routers.owncloud.tls.certresolver: cloudflare
      traefik.http.services.owncloud.loadbalancer.server.port: 9200
      # glance
      glance.name: ownCloud
      glance.icon: sh:ownCloud
      glance.url: https://owncloud.ryanmalonzo.com/

volumes:
  ocis:

networks:
  proxy:
    external: true
