services:
  traefik:
    image: traefik:v3.3
    container_name: traefik
    ports:
      - "443:443"
      # Web UI
      - "8081:8080"
    volumes:
      - ${VOLUMES_DIR}/traefik/traefik.yml:/etc/traefik/traefik.yml
      - ${VOLUMES_DIR}/traefik/dynamic.yml:/etc/traefik/dynamic.yml
      - ${VOLUMES_DIR}/traefik/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      CLOUDFLARE_EMAIL: ${CLOUDFLARE_EMAIL}
      CLOUDFLARE_DNS_API_TOKEN: ${CLOUDFLARE_DNS_API_TOKEN}
    networks:
      - proxy
    restart: unless-stopped
    labels:
      glance.name: Traefik
      glance.icon: sh:traefik

networks:
  proxy:
    external: true
