services:
  gluetun-protonvpn:
    image: qmcgaw/gluetun:v3.40
    container_name: gluetun-protonvpn
    cap_add:
      - NET_ADMIN
    volumes:
      - gluetun:/gluetun
    environment:
      VPN_SERVICE_PROVIDER: protonvpn
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY}
      SERVER_COUNTRIES: ${SERVER_COUNTRIES}
      WIREGUARD_IMPLEMENTATION: kernelspace
      WIREGUARD_MTU: 1420
      UPDATER_PERIOD: 24h
      TZ: ${TZ}
      FIREWALL_VPN_INPUT_PORTS: 41641
      FIREWALL_OUTBOUND_SUBNETS: 192.168.1.0/24,100.64.0.0/10,172.16.0.0/12
      DNS_ADDRESS: 192.168.1.96
    devices:
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped

  tailscale-protonvpn:
    image: tailscale/tailscale:v1.80
    container_name: tailscale-protonvpn
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY}?ephemeral=false
      TS_EXTRA_ARGS: --advertise-tags=tag:container,tag:vpn --advertise-exit-node
      TS_STATE_DIR: /var/lib/tailscale
      TS_HOSTNAME: protonvpn
    volumes:
      - tailscale:/var/lib/tailscale
    network_mode: service:gluetun-protonvpn
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

volumes:
  gluetun:
  tailscale:
