services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      LOG_LEVEL: debug
      TZ: ${TZ}
    volumes:
      - ${VOLUMES_DIR}/jellyseerr/config:/app/config
    networks:
      - ntfy
      - jellyfin
      - proxy
    restart: unless-stopped
    labels:
      # traefik
      traefik.enable: true
      traefik.http.routers.jellyseerr.rule: Host(`jellyseerr.ryanmalonzo.com`)
      traefik.http.routers.jellyseerr.entrypoints: websecure
      traefik.http.routers.jellyseerr.tls.certresolver: cloudflare
      traefik.http.services.jellyseerr.loadbalancer.server.port: 5055
      # glance
      glance.name: Jellyseerr
      glance.icon: sh:jellyseerr
      glance.url: https://jellyseerr.ryanmalonzo.com/

networks:
  ntfy:
    external: true
  jellyfin:
    external: true
  proxy:
    external: true
